runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /main.wasm
  mime_type: application/wasm
  static_files: main.wasm
  upload: main.wasm

- url: /(.*)
  static_files: \1
  upload: (.*)

skip_files:
  - app.yaml
